Added feature flag to disable Prometheus Histogram
opstree/druid-exporter pull request #102
Opened 2021-04-08 07:14 UTC by Stephan3555

Hi!

Prometheus Histogram is responsible for around 90% of the exported Metrics to Prometheus. After a short time the `/metrics` endpoint rose to several hundred MB.

Currently we do not have a usecase for histogram metrics.

I added a `--no-histogram` flag to disable the Histogram creation on demand.
I updated the Helm Chart accordingly.

The fork is running successfully on our environments without any issue

2021-04-08 07:59 UTC, Stephan3555 commented
Not sure about the failing compose test. I updated the compose file to already use the soon to be build tag 0.10

2021-04-12 03:12 UTC, iamabhishek-dubey requested changes

2021-04-12 03:12 UTC, iamabhishek-dubey commented on CHANGELOG.md
> +
CHANGELOG can be updated later, with some other BugFixes

2021-04-12 03:12 UTC, iamabhishek-dubey commented on compose/docker-compose.yml
>      container_name: druid_exporter
Till the time v0.10 is released, can we keep it v0.9?

2021-04-12 03:12 UTC, iamabhishek-dubey commented on helm/values.yaml
>    pullPolicy: IfNotPresent
Same thing here

2021-04-12 03:12 UTC, iamabhishek-dubey commented
Thanks for your valuable contribution, a few small comments I have added. Please go through them

2021-04-12 06:43 UTC, Stephan3555 commented on CHANGELOG.md
> +
Removed

2021-04-12 06:44 UTC, Stephan3555 commented on compose/docker-compose.yml
>      container_name: druid_exporter
Set back to 0.9

2021-04-12 06:44 UTC, Stephan3555 commented on helm/values.yaml
>    pullPolicy: IfNotPresent
Set back to 0.9

2021-04-12 06:44 UTC, Stephan3555 commented
Thanks for your feedback. I pushed the suggested changes

2021-04-12 09:12 UTC, iamabhishek-dubey approved these changes
LGTM

2021-04-12 09:12 UTC, merged